spring:
  application:
    name: yesul

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.yesul: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
