spring:
  application:
    name: yesul

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.yesul@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 20000
          timeout: 20000
          writetimeout: 20000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_KEY}
            client-secret: ${KAKAO_REST_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, account_email
            provider: kakao
          naver:
            client-id: ${NAVER_REST_KEY}
            client-secret: ${NAVER_REST_SECRET}
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            provider: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.yesul: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: false

app:
  image-upload:
    mode: ncp
    local-dir: upload-dir
    base-url: /images/

ncp:
  objectstorage:
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    bucket: ${NCP_BUCKET}
    access_key: ${NCP_ACCESS_KEY}
    secret_key: ${NCP_SECRET_KEY}
