spring:
  # 개발 서버용 데이터베이스 설정
  datasource:
    url: ${DEV_DATABASE_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      password: ${DEV_REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            # redirect-uri: http://223.130.132.13:8080/login/oauth2/code/kakao
            redirect-uri: https://yesul.shop/login/oauth2/code/kakao

          naver:
            # redirect-uri: http://223.130.132.13:8080/login/oauth2/code/naver
            redirect-uri: https://yesul.shop/login/oauth2/code/naver

google:
  redirect-uri: https://yesul.shop/admin/event/oauth2/callback